name: frog_back
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  common: 0.0.1
  dart_frog: ^0.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.21.7
  very_good_analysis: ^3.1.0
